services:
  - type: web
    name: NoisePollutionApp
    env: python
    region: oregon
    plan: free
    pythonVersion: 3.11
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn app:app
